using MedHelpAuthorizations.Domain.Entities.Enums;

namespace MedHelpAuthorizations.Infrastructure.DataPipe.Helpers
{
    public static class StateLookupHelper
    {
        public static readonly Dictionary<string, StateEnum> StateLookup = new Dictionary<string, StateEnum>(StringComparer.OrdinalIgnoreCase)
        {
                { "UNK", StateEnum.UNK },
                { "Unknown", StateEnum.UNK },
                { "AL", StateEnum.AL },
                { "Alabama", StateEnum.AL },
                { "AK", StateEnum.AK },
                { "Alaska", StateEnum.AK },
                { "AR", StateEnum.AR },
                { "Arkansas", StateEnum.AR },
                { "AZ", StateEnum.AZ },
                { "Arizona", StateEnum.AZ },
                { "CA", StateEnum.CA },
                { "California", StateEnum.CA },
                { "CO", StateEnum.CO },
                { "Colorado", StateEnum.CO },
                { "CT", StateEnum.CT },
                { "Connecticut", StateEnum.CT },
                { "DC", StateEnum.DC },
                { "D.C.", StateEnum.DC },
                { "DE", StateEnum.DE },
                { "Delaware", StateEnum.DE },
                { "FL", StateEnum.FL },
                { "Florida", StateEnum.FL },
                { "GA", StateEnum.GA },
                { "Georgia", StateEnum.GA },
                { "HI", StateEnum.HI },
                { "Hawaii", StateEnum.HI },
                { "IA", StateEnum.IA },
                { "Iowa", StateEnum.IA },
                { "ID", StateEnum.ID },
                { "Idaho", StateEnum.ID },
                { "IL", StateEnum.IL },
                { "Illinois", StateEnum.IL },
                { "IN", StateEnum.IN },
                { "Indiana", StateEnum.IN },
                { "KS", StateEnum.KS },
                { "Kansas", StateEnum.KS },
                { "KY", StateEnum.KY },
                { "Kentucky", StateEnum.KY },
                { "LA", StateEnum.LA },
                { "Louisiana", StateEnum.LA },
                { "MA", StateEnum.MA },
                { "Massachusetts", StateEnum.MA },
                { "MD", StateEnum.MD },
                { "Maryland", StateEnum.MD },
                { "ME", StateEnum.ME },
                { "Maine", StateEnum.ME },
                { "MI", StateEnum.MI },
                { "Michigan", StateEnum.MI },
                { "MN", StateEnum.MN },
                { "Minnesota", StateEnum.MN },
                { "MO", StateEnum.MO },
                { "Missouri", StateEnum.MO },
                { "MS", StateEnum.MS },
                { "Mississippi", StateEnum.MS },
                { "MT", StateEnum.MT },
                { "Montana", StateEnum.MT },
                { "NC", StateEnum.NC },
                { "North Carolina", StateEnum.NC },
                { "ND", StateEnum.ND },
                { "North Dakota", StateEnum.ND },
                { "NE", StateEnum.NE },
                { "Nebraska", StateEnum.NE },
                { "NH", StateEnum.NH },
                { "New Hampshire", StateEnum.NH },
                { "NJ", StateEnum.NJ },
                { "New Jersey", StateEnum.NJ },
                { "NM", StateEnum.NM },
                { "New Mexico", StateEnum.NM },
                { "NV", StateEnum.NV },
                { "Nevada", StateEnum.NV },
                { "NY", StateEnum.NY },
                { "New York", StateEnum.NY },
                { "OK", StateEnum.OK },
                { "Oklahoma", StateEnum.OK },
                { "OH", StateEnum.OH },
                { "Ohio", StateEnum.OH },
                { "OR", StateEnum.OR },
                { "Oregon", StateEnum.OR },
                { "PA", StateEnum.PA },
                { "Pennsylvania", StateEnum.PA },
                { "RI", StateEnum.RI },
                { "Rhode Island", StateEnum.RI },
                { "SC", StateEnum.SC },
                { "South Carolina", StateEnum.SC },
                { "SD", StateEnum.SD },
                { "South Dakota", StateEnum.SD },
                { "TN", StateEnum.TN },
                { "Tennessee", StateEnum.TN },
                { "TX", StateEnum.TX },
                { "Texas", StateEnum.TX },
                { "UT", StateEnum.UT },
                { "Utah", StateEnum.UT },
                { "VA", StateEnum.VA },
                { "Virginia", StateEnum.VA },
                { "VT", StateEnum.VT },
                { "Vermont", StateEnum.VT },
                { "WA", StateEnum.WA },
                { "Washington", StateEnum.WA },
                { "WI", StateEnum.WI },
                { "Wisconsin", StateEnum.WI },
                { "WV", StateEnum.WV },
                { "West Virginia", StateEnum.WV },
                { "WY", StateEnum.WY },
                { "Wyoming", StateEnum.WY }
        };
    }
}
