using MedHelpAuthorizations.Domain.Entities.Enums;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MedHelpAuthorizations.Domain.IntegratedServices;

namespace MedHelpAuthorizations.Infrastructure.Persistence.Initialization
{
    public partial class ApplicationDbSeeder
    {
        private async Task SeedClaimStatusExceptionReasonCategoryMaps()
        {
            List<ClaimStatusExceptionReasonCategoryMap> categoryMaps = new List<ClaimStatusExceptionReasonCategoryMap>()
            {
                //Authorization Denials
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "AUTHORIZATION REQUIRED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "NO AUTHORIZATION ON FILE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "NOT AUTHORIZED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "AUTH ON FILE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "EXCEED AUTHORIZED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "SERVICE NOT AUTHORIZED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "YOUR BENEFITS DON'T COVER CARE YOU GET FROM DOCTORS AND FACILITIES THAT AREN'T IN YOUR PLAN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial, "A PRIOR AUTHORIZATION WAS REQUIRED FOR THESE SERVICES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial,"PRIOR AUTHORIZATION IS REQUIRED FOR PAYMENT OF THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.AuthorizationDenial,"THE PROCEDURE BILLED IS NOT A COVERED SERVICE UNDER THE CLIENT'S BENEFIT PLAN."),
                

                //COB
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "COB DISALLOW"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "OTHER CARRIER PAYMENT INFORMATION NEEDED BEFORE CLAIM CAN BE PROCESSED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "PAYMENT FOR THESE SERVICES HAVE BEEN DENIED UNTIL REPLY TO COB QUESTIONNAIRE IS RECEIVED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "THIS CARE MAY BE COVERED BY ANOTHER PAYER PER COORDINATION OF BENEFITS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "MISSING PLAN INFORMATION FOR OTHER INSURANCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "YOU MUST FIRST SUBMIT A CLAIM FOR THIS CHARGE TO MEDICARE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "AFTER MEDICARE HAS PAID, PLEASE SEND YOUR CLAIM FOR BENEFITS TO YOUR LOCAL BLUE CROSS AND BLUE SHIELD PLAN OR THE PLAN SERVING THE AREA WHERE THE SERVICES WERE RENDERED. Ã‚Â BE SURE TO INCLUDE A COMPLETED FEDERAL EMPLOYEE PROGRAM HEALTH BENEFITS CLAIM FORM, THE MEDICARE SUMMARY NOTICE AND THE ITEMIZED BILLS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "THIS CARE MAY BE COVERED BY ANOTHER PAYER PER COORDINATION OF BENEFITS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "MISSING PLAN INFORMATION FOR OTHER INSURANCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "PLEASE SUBMIT THE PRIMARY CARRIER'S EOB FOR THIS SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "AN ATTACHMENT/OTHER DOCUMENTATION IS REQUIRED TO ADJUDICATE THIS CLAIM/SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "SECONDARY PAYMENT CANNOT BE CONSIDERED WITHOUT THE IDENTITY OF OR PAYMENT INFORMATION FROM THE PRIMARY PAYER. THE INFORMATION WAS EITHER NOTREPORTED OR WAS ILLEGIBLE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "MISSING PLAN INFORMATION FOR OTHER INSURANCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "ADDITIONAL INFORMATION IS NEEDED TO CONTINUE PROCESSING."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "CO-PAYMENT AMOUNT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "CHARGE EXCEEDS FEE SCHEDULE/MAXIMUM ALLOWABLE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "NETWORK BENEFITS HAVE BEEN APPLIED. THE MEMBER IS ONLY RESPONSIBLE FOR THE COST SHARE (DEDUCTIBLE, COPAY AND COINSURANCE) AND ANY NON-COVERED AMOUNT AFTER THEY MEET THEIR BENEFIT LIMIT FOR A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.COB, "THE CLAIM/LINE HAS BEEN DENIED.OTHER PAYER'S EXPLANATION OF BENEFITS/PAYMENT INFORMATION"),



                 //Claim Issue
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.ClaimIssue, "MISSING/INCOMPLETE/INVALID SERVICE FACILITY PRIMARY ADDRESS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.ClaimIssue, "N294 MISSING/INCOMPLETE/INVALID SERVICE FACILITY PRIMARY ADDRESS"),

                 //Demographics Issue
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.DemographicsIssue, "ERROR ON SUBMITTED REQUEST DATA. ENTITY'S DATE OF BIRTH"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.DemographicsIssue, "DATE OF BIRTH"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.DemographicsIssue, "INVALID/MISSING PATIENT NAME"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.DemographicsIssue, "MISSING/INCOMPLETE/INVALID PATIENT'S NAME"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.DemographicsIssue, "MEMBER DATE OF BIRTH DOES NOT MATCH DATE ON FILE"),                

                //Coding Issue
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE PROCEDURE IS NOT COVERED BY THIS CONTRACT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS SERVICE IS NOT PAID. ACCORDING TO CPT CODING GUIDELINES, THE MODIFIER IS NOT VALID IN COMBINATION WITH THE PROCEDURE CODE SUBMITTED. AN INTERNAL RULE, GUIDELINE OR PROTOCOL WAS RELIED UPON IN MAKING THIS ADVERSE BENEFIT DETERMINATION AND A COPY OF SUCH WILL BE PROVIDED FREE OF CHARGE UPON YOUR REQUEST"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS PROCEDURE IS NOT CONTRACTUALLY COVERED UNDER YOUR CONTRACT BASED ON THE DIAGNOSIS REPORTED. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE CLAIM CANNOT BE PROCESSED BECAUSE THE MEDICAL DOCUMENTATION THAT THE PROVIDER OF SERVICE SUPPLIED TO US IS INCOMPLETE. THE INFORMATION STILL NEEDED IS A STANDARD CPT OR NON-MEDICAID/NON-MEDICARE HCPCS CODE FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE PROCEDURE CODE IS INCONSISTENT WITH THE PROVIDER TYPE/SPECIALTY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE DIAGNOSIS IS INCONSISTENT WITH THE PATIENT'S GENDER. USAGE: REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110 SERVICE PAYMENT INFORMATAION REF), IF PRESENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "CLAIM/SERVICE DENIED/REDUCED BECAUSE \"NEW PATIENT\" QUALIFICATIONS WERE NOT MET.M13ONLY ONE INITIAL VISIT IS COVERED PER SPECIALTY PER MEDICAL GROUP"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "BENEFITS WERE NOT PAID FOR THIS CLAIM BECAUSE MEDICARE DID NOT RECEIVE THE CORRECT INFORMATION FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE DATE OF DEATH PRECEDES THE DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DENY - PLEASE SUBMIT TO FEE FOR SERVICE MEDICAID FOR PROCESSING"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DIAGNOSIS DOES NOT CORRESPOND TO PROCEDURE CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DIAGNOSIS NOT ALLOWED FOR BH CLAIMS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DID NOT MEET MINIMUM CASE RATE UNIT REQUIREMENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INAPPROPRIATE USE OF UA MODIFIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INVALID COMBINATION OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INVALID LOC/MODIFIER/PLACE OF SERVICE COMBINATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INVALID OR MISSING CPT4 OR HCPCS PROCEDURE CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MISSING ITEMIZED SERVICES FOR DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PRIMARY DIAGNOSIS IS NOT TYPICAL FOR PATIENT'S AGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PRIMARY DX LIMIT REACHED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROC CODE NOT FOUND ON ANY FEE SCHEDULE FOR MARYLAND MEDICAID PROGRAM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROCEDURE CODE FOR SERVICES RENDERED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROCEDURE CODE MUST BE BILLED WITH A PRIMARY CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "STANDALONE CODE CANNOT BE BILLED IN AN FQHC WITHOUT A TRIGGER CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "SUBMITTED COST IS REQUIRED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE TYPE OF BILL OR FREQUENCY CODE IS INVALID. PLEASE RESUBMIT WITH A CORRECTED CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROCEDURE CODE NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MISSING PROCEDURE MODIFIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROCEDURE CODE MODIFIER(S) FOR SERVICE(S) RENDERED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "BASED ON INDIVIDUAL CLAIM REVIEW, THE MODIFIER WAS NOT APPROPRIATELY BILLED AND WILL NOT OVERRIDE THE NCCI COLUMN I/COLUMN II EDIT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INAPPROPRIATE MODIFIER FOR SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "NDC CODE IS MISSING OR INVALID."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "CLAIM ADJUSTMENT REASON CODES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "16: CLAIM/SERVICE LACKS INFORMATION OR HAS SUBMISSION/BILLING ERROR(S)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "REMITTANCE ADVICE REMARK CODES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MA63: MISSING/INCOMPLETE/INVALID PRINCIPAL DIAGNOSIS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE DIAGNOSIS IS INCONSISTENT WITH THE PATIENT'S AGE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE PROCEDURE CODE IS INCONSISTENT WITH THE MODIFIER USED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "A REQUIRED MODIFIER IS MISSING."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "BENEFITS FOR THIS SERVICE ARE DENIED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE SERVICE CODE WASN'T SUBMITTED WITH AN APPROPRIATE MODIFIER."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS SERVICE CANNOT BE CONSIDERED FOR PAYMENT UNTIL WE RECEIVE THIS INFORMATION."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "SUBMIT A CORRECTED CLAIM WITH THE APPROPRIATE MODIFIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS SERVICE OR ITEM IS NOT REIMBURSABLE IN THIS PLACE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE PROCEDURE CODE/TYPE OF BILL IS INCONSISTENT WITH THE PLACE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MISSING/INCOMPLETE/INVALID/INAPPROPRIATE PLACE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "REIMBURSEMENT POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PAPDN: 001 PROC G0511 IS NOT REIMBURSABLE IN 11 PLACE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "POLICY: PROCEDURE TO PLACE OF SERVICE POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE SERVICE PERFORMED REQUIRES AN REFERRAL."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THERE IS NO REFERRAL ON FILE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "CLAIM/SERVICE LACKS INFORMATION OR HAS SUBMISSION/BILLING ERROR(S)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MISSING/INCOMPLETE/INVALID REFERRAL DATE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS PROVIDER WAS NOT CERTIFIED/ELIGIBLE TO BE PAID FOR THIS PROCEDURE/SERVICE ON THIS DATE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "A MODIFIER ON THE LINE IS NOT TYPICAL FOR THE PROCEDURE CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "CLIA CERTIFICATION LEVEL NOT MET"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE PROCEDURE CODE/BILL TYPE IS INCONSISTENT WITH THE PLACE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PROCEDURE INCONSISTENT WITH MODIFIER/REQUIRED MODIFIER MISSING"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "USE OF MODIFIER 95 IS INAPPROPRIATE FOR PROC 99213."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE REQUIRED MODIFIER FOR THIS VFC SERVICE IS MISSING."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "VACCINES FOR CHILDREN POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INVALID COMBINATION OF HCPCS MODIFIERS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "PRINCIPAL DIAGNOSIS INVALID. CODE CANNOT BE USED AS PRINCIPAL DX"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MISSING/INCOMPLETE/INVALID PRINCIPAL DIAGNOSIS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "New patient qualifications were not met"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "'NEW PATIENT' QUALIFICATIONS WERE NOT MET."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MEDICARE DENY ADD-ON PROCEDURE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "ADD-ON CODE CANNOT BE BILLED BY ITSELF."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THE BENEFIT FOR THIS SERVICE IS INCLUDED IN THE PAYMENT /ALLOWANCE FOR ANOTHER SERVICE/PROCEDURE THAT HAS ALREADY BEEN ADJUDICATED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "AN INCORRECT OR INAPPROPRIATE PRIMARY DIAGNOSIS CODE WAS USED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "001 DIAGNOSIS CODE F064 IS AN INAPPROPRIATE PRIMARY DIAGNOSIS CODE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "INAPPROPRIATE PRIMARY DIAGNOSIS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DIAGNOSIS NOT TYPICAL FOR AGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "THIS SHOULD BE BILLED WITH THE APPROPRIATE CODE FOR THESE SERVICES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "ONE OF THE DIAGNOSIS CODES IS NOT TYPICAL FOR AGE OF THIS PATIENT 18."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "AGE & GENDER TO DIAGNOSIS CODE & PROCEDURE CODE POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "CLAIM LINE DENIED DUE TO THE DIAGNOSIS CODES INCORRECTLY REPORTED PER ICD CODING GUIDELINES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DIAGNOSIS CODE POINTER IS MISSING OR INVALID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "DENY - SE MODIFIER IS REQUIRED WHEN BILLING VACCINE FOR CHILDREN <19"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "OPTUM RESPONSIBLE PRIMARY DIAGNOSIS AND SPECIALTY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "VFC CODES ARE NOT PAYABLE FOR MEMBERS => 19 YEARS OLD."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.CodingIssue, "MODIFIER U2 NOT ALLOWED"),



                //Contractual
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "CHARGE EXCEEDS ALLOWED AMOUNT FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "BILLED AMOUNT IS HIGHER THAN THE MAXIMUM ALLOWED PAYMENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "WE HAVE IDENTIFIED THAT THE PROCEDURE ON THIS CLAIM LINE WAS MUTUALLY EXCLUSIVE TO ANOTHER PROCEDURE PERFORMED BY THE SAME PROVIDER FOR THE SAME DATES OF SERVIVCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THE MEDICAL VISIT IS CUSTOMARILY PROVIDED WITH THE RELATED PROCEDURE. PAYMENT FOR THIS SERVICE IS INCLUDED IN THE PAYMENT MADE FOR THAT PROCEDURE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "PROCESSED PER PARTICIPATING CONTRACT OR FEE SCHEDULE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "PROCEDURE CODE INCIDENTAL TO PRIMARY PROCEDURE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THIS PROCEDURE IS NOT PAID SEPARATELY.THIS SERVICE/REPORT CANNOT BE BILLED SEPARATELY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THE SERVICE PERFORMED IS NOT COVERED UNDER THE PROVIDER'S CONTRACT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "SERVICE NOT PAYABLE PER MANAGED CARE CONTRACT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THIS DRUG/SERVICE/SUPPLY IS NOT INCLUDED IN THE FEE SCHEDULE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THE SERVICE PERFORMED IS INCLUDED IN THE CASE RATE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THE BENEFIT FOR THIS SERVICE IS INCLUDED IN THE PAYMENT /ALLOWANCE FOR ANOTHER SERVICE/PROCEDURE THAT HAS ALREADY BEEN ADJUDICATED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "CONSOLIDATED BILLING AND PAYMENT APPLIES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THIS NON-PAYABLE CODE IS FOR REQUIRED REPORTING ONLY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Contractual, "THIS PROCEDURE CODE IS FOR QUALITY REPORTING/INFORMATIONAL PURPOSES ONLY."),

                //Coverage
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "UNDER THIS MEMBER'S COVERAGE, BENEFITS ARE NOT AVAILABLE FOR THIS SERVICE. THEREFORE, WE ARE UNABLE TO PROVIDE BENEFITS FOR THIS CHARGE. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBER'S COVERAGE NOT IN EFFECT ON DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THESE CHARGES ARE NOT COVERED. THE SERVICES EXCEED THE MAXIMUM NUMBER OF UNITS ALLOWED PER THE MEMBER'S BENEFIT PLAN OR POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS SERVICE IS NOT A COVERED BENEFIT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "PATIENT NOT ENROLLED AT TIME OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE DATE OF SERVICE WAS PRIOR TO THE SUBSCRIBER'S EFFECTIVE DATE OF COVERAGE OR AFTER SUBSCRIBER'S CANCEL DATE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "SERVICES IDENTIFIED BY THIS DIAGNOSIS, PROCEDURE, OR SURGICAL CODENOT COVERED UNDER THE MEMBER'S COVERAGE. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATON"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS PROCEDURE CODE IS NOT A COVERED BENEFIT UNDER THE MEMBER'S COVERAGE. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "SERVICES FOR DIAGNOSIS REPORTED ARE NOT A BENEFIT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "BENEFITS ARE NOT PROVIDED FOR SERVICES OBTAINED FROM NON-PARTICIPATING PROVIDERS PER THE MEMBER'S BENEFIT PLAN OR POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS SERVICE WAS PERFORMED PRIOR TO THE EFFECTIVE DATE OR AFTER THE CANCELLATION DATE OF YOUR PARTICIPATING STATUS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "ACCORDING TO OUR RECORDS, THIS PATIENT'S COVERAGE WAS NOT IN EFFECT ON THE DATE THESE SERVICES WERE RENDERED. THEREFORE, WE ARE UNABLE TO PROVIDE BENEFITS FOR THESE CHARGES. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "SERVICES IDENTIFIED BY THIS DIAGNOSIS, PROCEDURE, OR SURGICAL CODEARE NOT COVERED UNDER THE MEMBER'S COVERAGE. PLEASE REFERTO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS SERVICE IS NOT COVERED UNDER THE MEMBER'S PLAN"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THESE SERVICES WERE PROVIDED AFTER YOU CHANGED YOUR COVERAGE TO ANOTHER CARRIER UNDER THE FEDERAL EMPLOYEES HEALTH BENEFITS PROGRAM. Ã‚Â YOU SHOULD SUBMIT THESE CHARGES TO YOUR NEW CARRIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "PLAN NOT EFFECTIVE ON DATE REQUESTED "),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "UNDER THIS MEMBER'S COVERAGE, BENEFITS ARE NOT AVAILABLE FOR THIS SERVICE. THEREFORE, WE ARE UNABLE TO PROVIDE BENEFITS FOR THIS CHARGE. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE MEMBERS CONTRACT WAS NOT IN EFFECT ON THE DATE OF SERVICE. IF YOU DISAGREE WITH THIS DETERMINATION, PLEASE CONTACT YOUR EMPLOYER. PLEASE REFER TO THE EMPLOYEE BENEFIT BOOKLET OR CONTRACT FOR ADDITIONAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "BENEFITS ARE NOT PROVIDED FOR SERVICES/SUPPLIES LISTED IN THE GENERAL EXCLUSIONS SECTION OF THE BLUE CROSS BLUE SHIELD SERVICE BENEFIT PLAN BROCHURE. Ã‚Â YOU ARE RESPONSIBLE FOR THESE CHARGES EVEN IF THE SERVICES/SUPPLIES WERE ORDERED BY A PROVIDER, EXCEPT WHEN ANOTHER CARRIER HAS PAID FOR THE SERVICE(S) IN FULL"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "EXPENSES INCURRED PRIOR TO COVERAGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "SERVICES NOT COVERED BECAUSE THE PATIENT IS ENROLLED IN A HOSPICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "DATE OF SERVICE NOT COVERED/AUTHORIZED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "DENIED CHARGE OR NON-COVERED CHARGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "EXPENSES INCURRED PRIOR TO COVERAGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "ONLY ONE INITIAL VISIT IS COVERED PER SPECIALTY PER MEDICAL GROUP"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NOT COVERED WHEN PERFORMED DURING THE SAME SESSION/DATE AS A PREVIOUSLY PROCESSED SERVICE FOR THE PATIENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "INVESTIGATING EXISTENCE OF OTHER INSURANCE COVERAGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "LAPSE IN COVERAGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBER'S HEALTHCARE COVERAGE WAS TERMINATED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "FINALIZED/DENIAL-THE CLAIM/LINE HAS BEEN DENIED.POLICY CANCELED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MISSING WORK STATUS REPORT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "INFORMATION REQUESTED WAS NOT PROVIDED OR WAS INSUFFICIENT/INCOMPLETE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NO BENEFIT IS DUE BECAUSE THIS CODE WAS BILLED FOR ZERO DOLLARS OR SHOULD HAVE BEEN BILLED FOR ZERO DOLLARS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS NON-PAYABLE CODE IS FOR REQUIRED REPORTING ONLY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NON-COVD SVC BY PLAN"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NON-COVERED CHARGE(S)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS DRUG/SERVICE/SUPPLY IS NOT INCLUDED IN THE FEE SCHEDULE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE FOLLOWING CODE 90460 IS NOT A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NON COVERED CODES POLICY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE FOLLOWING CODE 90461 IS NOT A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE FOLLOWING CODE 90471 IS NOT A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE FOLLOWING CODE 90649 IS NOT A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "PROCEDURE CODE INCLUDED IN ANOTHER SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "SEPARATELY BILLED SERVICES/TESTS HAVE BEEN BUNDLED AS THEY ARE CONSIDERED COMPONENTS OF THE SAME PROCEDURE. SEPARATE PAYMENT IS NOT ALLOWED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "CODE IS NOT PAYABLE - FOR INFORMATIONAL PURPOSES ONLY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE FOLLOWING CODE 3008F IS A NON-COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEDICARE UNBUNDLED SCENARIO"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THIS PROCEDURE IS NOT PAID SEPARATELY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "NOT COVERED WHEN PERFORMED DURING THE SAME SESSION/DATE AS A PREVIOUSLY PROCESSED SERVICE FOR THE PATIENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "EXPENSES INCURRED PRIOR TO COVERAGE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "PATIENT INELIGIBLE FOR THIS SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBER NOT ELIGIBLE FOR BENEFITS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "DATE REQ. PRIOR TO SUBSCRIBER EFF DT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "EXPENSES INCURRED AFTER COVERAGE TERMINATED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "YOUR SEARCH RETURNED NO POLICIES; HOWEVER, POLICIES WERE FOUND OUTSIDE OF THE ENTERED DATE RANGE. PLEASE UPDATE THE SERVICE DATES AND TRY AGAIN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MISSING THE SUBSCRIBER FIRST OR LAST NAME, OR THE MATCHING ALGORITHM FAILED TO FIND A MATCH BASED ON THE NAME IN THE HETS DATABASE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBER IS ADDED TO WRONG PAYER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE BENEFICIARY'S ENTITLEMENT FOR MEDICARE COVERAGE WAS TERMINATED PRIOR TO THE FIRST DATE FOR SERVICES PROVIDED ON THE CLAIM. THEREFORE, NO MEDICARE PAYMENT CAN BE MADE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE CENTERS FOR MEDICARE AND MEDICAID SERVICES RECORDS INDICATE THAT THE BENEFICIARY IS NOT ENTITLED TO MEDICARE COVERAGE FOR THE TYPE OF SERVICES BILLED ON THE CLAIM. THEREFORE, NO MEDICARE PAYMENT CAN BE MADE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "YOUR PLAN DOES NOT PROVIDE COVERAGE FOR THESE EXPENSES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "THE SUBMITTED PROCEDURE IS DISALLOWED BECAUSE IT IS INCIDENTAL TO A CODE BILLED ON THE SAME DATE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "CODE FOR DOCUMENTATION PURPOSES ONLY. NO SEPARATE REIMBURSEMENT WARRANTED. NOT PAID. DO NOT BILL MEMBER."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBER NOT ELIGIBLIE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "MEMBERNOTFOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Coverage, "YOUR SEARCH RETURNED NO RESULTS. PLEASE REVIEW YOUR SEARCH CRITERIA, INCLUDING THE PAYER NAME/PAYER ID, AND TRY AGAIN."),


                //Credentialing
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS CLAIM WAS RECEIVED BY A PROVIDER IN YOUR GROUP PRACTICE WHO, ACCORDING TO OUR RECORDS, DID NOT PARTICIPATE WITH CAREFIRST BLUE CROSS BLUE SHIELD AT THE TIME THE SERVICES WERE RENDERED. IT IS OUR POLICY THAT ALL PROVIDERS WITHIN A GROUP PRACTICE MUST APPLY AND BE ACCEPTED FOR PARTICIPATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "BILLING PHYSICIAN IS NOT PAR WITH GROUP"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS PROVIDER WAS NOT CERTIFIED/ELIGIBLE TO BE PAID FOR THIS PROCEDURE/SERVICE ON THIS DATE OF SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE REFERRING PROVIDER IS NOT ELIGIBLE TO REFER THE SERVICE BILLED. USAGE: REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110 SERVICE PAYMENT INFORMATION REF), IF PRESENT.MA13ALERT: YOU MAY BE SUBJECT TO PENALTIES IF YOU BILL THE BENEFICIARY FOR AMOUNTS NOT REPORTED WITH THE PR (PATIENT RESPONSIBILITY) GROUP CODE.N574OUR RECORDS INDICATE THE ORDERING/REFERRING PROVIDER IS OF A TYPE/SPECIALTY THAT CANNOT ORDER OR REFER. PLEASE VERIFY THAT THE CLAIM ORDERING/REFERRING PROVIDER INFORMATION IS ACCURATE OR CONTACT THE ORDERING/REFERRING PROVIDER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "BILLING PROVIDER ENROLLMENT IS TERMINATED WITH MD MEDICAID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "ENTITY IS NOT SELECTED PRIMARY CARE PROVIDER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "ENTITY NOT ELIGIBLE FOR BENEFITS FOR SUBMITTED DATES OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "ENTITY'S MEDICAID PROVIDER ID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "NO AGREEMENT WITH ENTITY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "RENDERING PROV MUST BE AN ACTIVE MEDICAID PROVIDER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "RENDERING PROVIDER ENROLLMENT IS SUSPENDED WITH MD MEDICAID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "RENDERING PROVIDER REQUIRED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "PAYMENT IS DENIED WHEN BILLED BY THIS PROV TYPE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "RENDERING PROV TYPE NOT ELIGIBLE FOR PROV GROUP"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "CLAIM NOT FOUND, CLAIM SHOULD HAVE BEEN SUBMITTED TO/THROUGH 'ENTITY'. THIS PERTAINS TO THE PROVIDER ENTITY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "ENTITY NOT FOUND."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE BILLING TAXONOMY IS MISSING OR INVALID. RESUBMIT CLAIM WITH VALID BILLING TAXONOMY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE PAYER COULD NOT FIND ANY RESULTS BASED ON YOUR SEARCH. PLEASE REFINE YOUR SEARCH CRITERIA "),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "ENTITY'S ID NUMBER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE PROVIDER TYPE/SPECIALTY OR LOCATION MAY NOT BILL FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE PROCEDURE CODE IS INCONSISTENT WITH THE PROVIDER TYPE/SPECIALTY (TAXONOMY)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "MISSING/INCOMPLETE/INVALID CREDENTIALING DATA."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "CHARGE EXCEEDS FEE SCHEDULE/MAXIMUM ALLOWABLE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS PROVIDER TYPE/PROVIDER SPECIALTY MAY NOT BILL THIS SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "NO AUTHORIZATION ON FILE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "PRECERTIFICATION/AUTHORIZATION/NOTIFICATION/ PRE-TREATMENT ABSENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS PROVIDER IS NOT ELIGIBLE TO BILL FOR SERVICES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "USAGE: REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110 SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "MISSING/INCOMPLETE/INVALID CREDENTIALING DATA."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "MISSING/INCOMPLETE/INVALID REFERRING PROVIDER PRIMARY IDENTIFIER."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "PRE-CERTIFICATION/AUTHORIZATION/NOTIFICATION ABSENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "PRECERTIFICATION/AUTHORIZATION/NOTIFICATION/ PRE-TREATMENT ABSENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS PROVIDER TYPE/PROVIDER SPECIALTY MAY NOT BILL THIS SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE PCP HAS NOT BEEN SELECTED OR DOESN'T MATCH THE PCP ON FILE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "MEMBER NEEDS TO CONTACT THE CUSTOMER SERVICE DEPARTMENT AT THE PHONE NUMBER LISTED ON THE IDENTIFICATION CARD TO SELECT A PRIMARY CARE PHYSICIAN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE MEMBER IS RESPONSIBLE FOR THE OUTSTANDING CHARGES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "SERVICES NOT PROVIDED BY NETWORK/PRIMARY CARE PROVIDERS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "PROVIDER IS NOT ELIGIBLE FOR PROCEDURE ON DATE OF SERVICE,THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO,PROCEDURE NOT ALLOWED ON DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THE RENDERING PROVIDER IS NOT ELIGIBLE TO PERFORM THE SERVICE BILLED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "THIS CHARGE IS DENIED BASED ON THE PROCEDURE CODE YOUR PROVIDER USED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "RENDERING CLINICIAN HAS NOT BEEN INDIVIDUALLY CREDENTIALED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "003 PROCEDURE CODE 99213 IS NOT ALLOWED WHEN BILLED BY A NONPHYSICIAN HEALTH CARE PROFESSIONAL."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Credentialing, "NONPHYSICIAN HEALTH CARE PROFESSIONALS BILLING EVALUATION AND MANAGEMENT CODES"),



                //Duplicate
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CLAIM LINE IS AN EXACT DUPLICATE OF ANOTHER CLAIM LINE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "ALL SUBMISSIONS DENIED AS DUPLICATE OF THE OTHER, NO ORIGINAL LINE ITEM WITH A DIFFERENT STATUS FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CLAIM LINE IS AN EXACT DUPLICATE OF ANOTHER CLAIM LINE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "ANOTHER PROVIDER HAS BILLED FOR THE SERVICES DESCRIBED IN THIS CLAIM. PAYMENT OF THIS SERVICE, THEREFORE, WOULD RESULT IN A DUPLICATE PAYMENT ACCORDING TO THE ADMINISTRATION PROVISIONS OF THE SUBSCRIBERS CONTRACT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CLAIM IS A DUPLICATE OF A PREVIOUSLY SUBMITTED CLAIM FOR THIS MEMBER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CHARGE/BILL IS A DUPLICATE OF ANOTHER YOU INCLUDED WITH THIS CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CLAIM IS A DUPLICATE OF A CLAIM CURRENTLY IN PROCESS. YOU WILL RECEIVE AN EXPLANATION WHEN WE HAVE COMPLETED PROCESSING OF THE ORIGINAL CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "EXACT DUPLICATE CLAIM/SERVICE (USE ONLY WITH GROUP CODE OA EXCEPT WHERE STATE WORKERS' COMPENSATION REGULATIONS REQUIRES CO)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "YOU HAVE ALREADY RECEIVED CREDIT TOWARD YOUR DEDUCTIBLE OR RECEIVED BENEFITS FOR THIS CHARGE ON A PREVIOUS CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "BILLED MORE THAN ONCE/DAY WITH HISTORY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "WE HAVE IDENTIFIED THAT THE PROCEDURE CODE ON THIS CLAIM LINE IS A DUPLICATE PROCEDURE AND SHOULD NOT BE REIMBURSED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE CLAIM/SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE OF A CLAIM PROCESSED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE CLAIM PREVIOUSLY PROCESSED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "THIS CLAIM IS A DUPLICATE OF A PREVIOUSLY SUBMITTED CLAIM FOR THIS MEMBER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE OF A CLAIM PROCESSED, OR TO BE PROCESSED, AS A CROSSOVER CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Duplicate, "DUPLICATE OF A PREVIOUSLY PROCESSED CLAIM/LINE"),

                //Insurance Termed
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "TERMINATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "TERMINATION - NON PAYMENT OF PREMIUM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "HAS BEEN TERMINATED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "DATE REQUESTED AFTER GROUP TERM DATE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "THE MEMBERS CONTRACT WAS NOT IN EFFECT ON THE DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "AFTER COVERAGE TERMINATED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InsuranceTermed, "POLICY CANCELED"),

                //Invalid Insurance                
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InvalidInsurance, "WE HAVE NO RECORD OF THE IDENTIFICATION NUMBER SUBMITTED FOR THIS SUBSCRIBER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InvalidInsurance, "THE MEMBERS CONTRACT WAS NOT IN EFFECT ON THE DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InvalidInsurance, "YOU MUST FIRST SUBMIT A CLAIM FOR THIS CHARGE TO MEDICARE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InvalidInsurance, "THE DATE OF SERVICE WAS PRIOR TO THE SUBSCRIBER'S EFFECTIVE DATE OF COVERAGE OR AFTER SUBSCRIBER'S CANCEL DATE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.InvalidInsurance, "EXPENSES INCURRED PRIOR TO COVERAGE"),

                //Medical Necessity
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MedicalNecessity, "THESE ARE NON-COVERED SERVICES BECAUSE THIS IS NOT DEEMED A 'MEDICAL NECESSITY' BY THE PAYER"),                
               
                //MR Needed
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MRNeeded, "FINAL BENEFIT DETERMINATION CANNOT BE MADE UNTIL WE RECEIVE SPECIFIC REQUESTED MEDICAL INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MRNeeded, "BEFORE WE CAN REVIEW YOUR CLAIM, WE NEED TO KNOW THE SPECIFIC ILLNESS, INJURY, CONDITION OR DIAGNOSIS THAT REQUIRED TREATMENT. WE WILL RECONSIDER YOUR CLAIM ONCE WE RECEIVE THIS INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MRNeeded, "YOUR CLAIM IS CURRENTLY BEING REVIEWED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MRNeeded, "CLAIM CANNOT BE PROCESSED BECAUSE THE MEDICAL DOCUMENTATION"),

                //NO Claim / Missing Procedure
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIM NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "UNMATCHED-PROCEDURECODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIMS WERE NOT FOUND THAT MATCHED THE CRITERIA GIVEN"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "PROCEDURE CODE NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "PROCEDURE CODE NOT FOUND IN CLAIM LINES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "0 CLAIMS FOUND WITH THE PROVIDED CRITERIA IN THE INCEDO APPLICATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "ACKNOWLEDGEMENT NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "NO CLAIMS/ENCOUNTERS FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "ACKNOWLEDGEMENT/NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIM/ENCOUNTER NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "ENTITY NOT ELIGIBLE FOR BENEFITS FOR SUBMITTED DATES OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIM UNAVAILABLE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "THE CLAIM/ENCOUNTER CAN NOT BE FOUND IN THE ADJUDICATION SYSTEM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "DATA SEARCH UNSUCCESSFUL"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIM/ENCOUNTER NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "MEMBER FOUND, BUT NO CLAIM FOUND."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "PLEASE RECHECK YOUR ENTRIES FOR PAYER ID AND CARE PROVIDER SELECTION (IN TOP RIGHT HAND CORNER) AS WELL AS YOUR DATE OF SERVICE TO ENSURE THEY ARE CORRECT. IF RECENTLY BILLED, THE CLAIM MAY NOT BE AVAILABLE ONLINE AT THIS TIME."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "PLEASE CHECK THE MEMBER INFORMATION ENTERED, AS A CLAIM CANNOT BE FOUND MATCHING THE INFORMATION ENTERED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "PLEASE REENTER, TRY A DIFFERENT SEARCH TYPE OR ENSURE THE RADIO BUTTON LABELED \"TIN\" IS SELECTED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.NoClaimMissingProcedure, "CLAIM STILL UNAVAILABLE IN PAYERS SYSTEM AFTER 10 DAYS SINCE BILLED."),


                //Other
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "AIT IS CURRENTLY UNABLE TO REVIEW THIS CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "ALERT: YOU MAY NOT APPEAL THIS DECISION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "STATUTORILY EXCLUDED SERVICES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "PROCESSED ACCORDING TO CONTRACT PROVISIONS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110  SERVICE PAYMENT INFORMATION REF)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Other, "ACCEPTED FOR PROCESSING"),

                //Policy Number
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "THE MEMBER'S HOME PLAN HAS ADVISED US THAT THE PREFIX FOR THIS ID NUMBER IS INCORRECT.PLEASE DO NOT RESUBMIT THE CLAIM AS WE WILL HAVE IT REPROCESSED CORRECTLY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "SUBSCRIBER AND SUBSCRIBER ID NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "MEDICARE BENEFICIARY ID IS INVALID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "MISSING/INCOMPLETE/INVALID PATIENT/IDENTIFIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "INVALID/MISSING SUBSCRIBER/INSURED NAME - PLEASE CORRECT AND RESUBMIT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "RESPONSE NOT POSSIBLE - ERROR ON SUBMITTED REQUEST DATA. PATIENT'S ID NUMBER."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "MEMBER ID IS EMPTY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "MEMBERNOTFOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "NO CLAIM LINE ITEMS FOUND!!"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.PolicyNumber, "NO MEDICAID NUMBER AND/OR DISCLOSURE FORM"),

                //Provider Type
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.ProviderType, "PAYMENT IS DENIED WHEN BILLED BY THIS PROV TYPE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.ProviderType, "THIS CLAIM WAS RECEIVED BY A PROVIDER IN YOUR GROUP PRACTICE WHO, ACCORDING TO OUR RECORDS, DID NOT PARTICIPATE WITH CAREFIRST BLUE CROSS BLUE SHIELD AT THE TIME THE SERVICES WERE RENDERED. IT IS OUR POLICY THAT ALL PROVIDERS WITHIN A GROUP PRACTICE MUST APPLY AND BE ACCEPTED FOR PARTICIPATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.ProviderType, "RENDERING PROV TYPE NOT ELIGIBLE FOR PROV GROUP"),
                
                //Internal Review
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MEMBER ID IGNORED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS CLAIM CANNOT BE PROCESSED WITHOUT ADDITIONAL INFORMATION. Â HOWEVER, SINCE YOUR PROVIDER IS A PARTICIPATING OR PREFERRED PROVIDER, YOU ARE NOT RESPONSIBLE FOR THESE CHARGES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS CLAIM CANNOT BE PROCESSED WITHOUT ADDITIONAL INFORMATION.  HOWEVER, SINCE YOUR PROVIDER IS A PARTICIPATING OR PREFERRED PROVIDER, YOU ARE NOT RESPONSIBLE FOR THESE CHARGES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THESE SERVICES ARE INELIGIBLE AS THEY ARE NOT CONSIDERED MEDICALLY NECESSARY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BENEFITS FOR THIS SERVICE HAVE BEEN PAID TO ANOTHER PROVIDER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "N/A"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "YOUR ADJUSTMENT REQUEST WAS RECEIVED AND THE ORIGINAL CLAIM WAS ADJUSTED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "N/A"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "N/A"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "N/A"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PENDING/PAYER ADMINISTRATIVE/SYSTEM HOLD,46 - INTERNAL REVIEW/AUDIT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE SERVICES RENDERED WERE NOT BILLED USING THE AGREED UPON FORMAT. THE PROVIDER IS PARTICIPATING, THEREFORE, THE PATIENT IS NOT RESPONSIBLE FOR PAYMENT OF THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BENEFITS FOR THESE SERVICES ARE INCLUDED IN OUR ALLOWABLE CHARGES FOR ANOTHER COVERED SERVICE PROVIDED ON THE SAME DATE OF SERVICE.  ADDITIONAL BENEFITS ARE NOT AVAILABLE FOR THIS CHARGE.  BECAUSE THIS PROVIDER IS A PREFERRED OR PARTICIPATING NETWORK PROVIDER, YOU ARE NOT RESPONSIBLE FOR THESE CHARGES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MEMBER NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MEMBER WAS NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MEMBER WAS NOT SUCESSFULLY FOUND OR MORE THAN ONE MEMBER FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "N/A"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BENEFITS ARE NOT PROVIDED FOR SERVICES/SUPPLIES LISTED IN THE GENERAL EXCLUSIONS SECTION OF THE BLUE CROSS BLUE SHIELD SERVICE BENEFIT PLAN BROCHURE.Â YOU ARE RESPONSIBLE FOR THESE CHARGES EVEN IF THE SERVICES/SUPPLIES WERE ORDERED BY A PROVIDER, EXCEPT WHEN ANOTHER CARRIER HAS PAID FOR THE SERVICE(S) IN FULL"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BENEFITS WERE NOT PAID FOR THIS CLAIM BECAUSE MEDICARE DID NOT RECEIVE THE CORRECT INFORMATION FOR THIS SERVICE. YOUR CLAIM WILL BE PROCESSED AS SOON AS YOUR PHYSICIAN SENDS THE CORRECT INFORMATION TO MEDICARE. THANK YOU FOR YOUR PATIENCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "REIMBURSEMENT FOR THIS SERVICE IS CONSIDERED TO BE A PORTION OF ANOTHER SERVICE WHICH HAS BEEN ALLOWED. THEREFORE, NO PAYMENT CAN BE MADE FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS LINE OF BUSINESS IS PROCESSED BY A VENDOR. HANDLE DIRECT WITH VENDOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "OUR CONTRACT WITH THIS PROVIDER INCLUDES THIS SERVICE WITHIN THE REIMBURSEMENT OF ANOTHER SERVICE AND, THEREFORE, DOES NOT ALLOW SEPARATE PAYMENT OF BENEFITS. IF THE PROVIDER IS PARTICIPATING WITH OUR PLAN. THE MEMBER IS NOT RESPONSIBLE FOR THE PAYMENT OF THIS SERVICE. AN INTERNAL RULE, GUIDELINE, OR PROTOCOL WAS RELIED UPON IN MAKING THIS ADVERSE BENEFIT DETERMINATION AND A COPY OF SUCH WILL BE PROVIDED FREE OF CHARGE UPON YOUR REQUEST"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BENEFITS FOR THESE SERVICES ARE INCLUDED IN OUR ALLOWABLE CHARGES FOR ANOTHER COVERED SERVICE PROVIDED ON THE SAME DATE OF SERVICE. ADDITIONAL BENEFITS ARE NOT AVAILABLE FOR THIS CHARGE. BECAUSE THIS PROVIDER IS A PREFERRED OR PARTICIPATING NETWORK PROVIDER, YOU ARE NOT RESPONSIBLE FOR THESE CHARGES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "OUR CONTRACT WITH THIS PROVIDER INCLUDES THIS SERVICE WITHIN THE REIMBURSEMENT OF ANOTHER SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "REJECT EOB"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE DATE OF DEATH PRECEDES THE DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PAYMENT ADJUSTED BECAUSE THE PAYER DEEMS THE INFORMATION SUBMITTED DOES NOT SUPPORT THIS MANY/FREQUENCY OF SERVICES.MA01ALERT: IF YOU DO NOT AGREE WITH WHAT WE APPROVED FOR THESE SERVICES, YOU MAY APPEAL OUR DECISION. TO MAKE SURE THAT WE ARE FAIR TO YOU, WE REQUIRE ANOTHER INDIVIDUAL THAT DID NOT PROCESS YOUR INITIAL CLAIM TO CONDUCT THE APPEAL. HOWEVER, IN ORDER TO BE ELIGIBLE FOR AN APPEAL, YOU MUST WRITE TO US WITHIN 120 DAYS OF THE DATE YOU RECEIVED THIS NOTICE, UNLESS YOU HAVE A GOOD REASON FOR BEING LATE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM/SERVICE LACKS INFORMATION OR HAS SUBMISSION/BILLING ERROR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NON-COVERED CHARGE(S). AT LEAST ONE REMARK CODE MUST BE PROVIDED (MAY BE COMPRISED OF EITHER THE NCPDP REJECT REASON CODE, OR REMITTANCE ADVICE REMARK CODE THAT IS NOT AN ALERT.) USAGE: REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110 SERVICE PAYMENT INFORMATION REF), IF PRESENT.N425STATUTORILY EXCLUDED SERVICES(S)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE BENEFIT FOR THIS SERVICE IS INCLUDED IN THE PAYMENT/ALLOWANCE FOR ANOTHER SERVICE/PROCEDURE THAT HAS ALREADY BEEN ADJUDICATED. USAGE: REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110 SERVICE PAYMENT INFORMATION REF), IF PRESENT.N211ALERT: YOU MAY NOT APPEAL THIS DECISION.N666ONLY ONE EVALUATION AND MANAGEMENT CODE AT THIS SERVICE LEVEL IS COVERED DURING THE COURSE OF CARE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SERVICES NOT COVERED BECAUSE THE PATIENT IS ENROLLED IN A HOSPICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS SERVICE IS NOT COVERED BECAUSE IT IS CONSIDERED EXPERIMENTAL"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM WAS PROCESSED AS ADJUSTMENT TO PREVIOUS CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "HOWEVER, IN ORDER TO BE ELIGIBLE FOR AN APPEAL, YOU MUST WRITE TO US WITHIN 120  DAYS OF THE DATE YOU RECEIVED THIS NOTICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PLEASE SUBMIT COPY OF PRIMARY INSURANCE EXPLANATION OF PAYMENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "RECOUPMENT HAS BEEN MADE DUE TO AN UPDATE TO THE PROVIDER'S FEE SCHEDULE WHICH NOW RESULTED IN AN OVERPAYMENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "RECOUPMENT MADE DUE TO AN INCORRECT BENEFIT PREVIOUSLY PAID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "UNIT OF SERVICE EXCEEDS MAXIMUM ALLOWED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "POLICY NUMBER NOT REVIEWABLE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CORRECTED CLAIM CANNOT BE MATCHED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM HAS BEEN PROCESSED"),// So far .. these are found to be paid with no check - Approved
                //This is for a "PAID" claim, but it indicates a "Takeback" from another claim and needs to be reviewed
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "ORIGINAL CLAIM HAS BEEN ADJUSTED BY FULL CLAIM ADJ"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "BECAUSE THIS PROVIDER IS A PREFERRED OR PARTICIPATING NETWORK PROVIDER, YOU ARE NOT RESPONSIBLE FOR THE DIFFERENCE BETWEEN THE SUBMITTED CHARGES AND OUR ALLOWABLE CHARGES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CANNOT PROVIDE FURTHER STATUS ELECTRONICALLY"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "REFER TO THE 835 HEALTHCARE POLICY IDENTIFICATION SEGMENT (LOOP 2110  SERVICE PAYMENT INFORMATION REF)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROCESSED ACCORDING TO PLAN PROVISIONS (PLAN REFERS TO PROVISIONS THAT EXIST BETWEEN THE HEALTH PLAN AND THE CONSUMER OR PATIENT)"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE HEALTH PLAN IS DOWN FOR MAINTENANCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "ERROR ON SUBMITTED REQUEST DATA. SUBMITTER NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MISSING OR INVALID INFORMATION"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "INVALID/MISSING PATIENT ID"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CHARGE EXCEEDS FEE SCHEDULE/MAXIMUM ALLOWABLE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT. USAGE: THIS ADJUSTMENT AMOUNT CANNOT EQUAL THE TOTAL SERVICE OSHOW MORE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "AT LEAST ONE REMARK CODE MUST BE PROVIDED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "FINALIZED-THE CLAIM/ENCOUNTER HAS COMPLETED THE ADJUDICATION CYCLE AND NO MORE ACTION WILL BE TAKEN.DENIED CHARGE OR NON-COVERED CHARGE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "IT LACKS A REQUIRED QUALIFYING VISIT CODE FROM A FEDERALLY QUALIFIED HEALTH CENTER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROCEDURE CODE NOT FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SEE YOUR EVIDENCE OF COVERAGE TO KNOW IF YOUR PLAN INCLUDES A PART D PRESCRIPTION DRUG BENEFIT AND HOW TO REQUEST REIMBURSEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SERVICE NOT PAYABLE PER MANAGED CARE CONTRACT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SUBMIT TO PHARMACY CARRIER/VENDOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SUBMITTED LINE IS DISALLOWED BECAUSE CODE PAIRS FOUND IN HISTORY TO BE UNBUNDLED ACCORDING TO CMS NATIONAL CORRECT CODING INITIATIVE (NCCI)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE BENEFIT FOR THIS SERVICE IS INCLUDED IN THE PAYMENT/ALLOWANCE FOR ANOTHER SERVICE/PROCEDURE THAT HAS ALREADY BEEN ADJUDICATED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS SERVICE IS NOT ALLOWED PER MEDICARE PAYMENT STANDARDS. THE MEMBER IS NOT RESPONSIBLE FOR PAYMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "IT WAS SUBMITTED FOR SERVICES THAT ARE NOT ALLOWED BASED ON OUR CONTRACT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM IS SAME AS PREVIOUS, SO IGNORING"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "DENIED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NO CLAIM LINE ITEMS FOUND!! STATUS: DENIED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THESE ARE NON-COVERED SERVICES BECAUSE THIS IS NOT DEEMED A 'MEDICAL NECESSITY' BY THE PAYER."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS DECISION WAS BASED ON A NATIONAL COVERAGE DETERMINATION (NCD)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "AN NCD PROVIDES A COVERAGE DTERMINATION AS TO WHETHER A PARTICULAR ITEM OR SERVICE IS COVERED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "A COPY OF THIS POLICY IS AVAILABLE AT WWW.CMS.GOV/MCD/SEARCH.ASP."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "IF YOU DO NOT HAVE WEB ACCESS, YOU MAY CONTACT THE CONTRACTOR TO REQUEST A COPY OF THE NCD."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "ADD-ON CODE CANNOT BE BILLED BY ITSELF."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE PAYMENT/ALLOWANCE FOR ANOTHER SERVICE /PROCEDURE THAT HAS ALREADY BEEN ADJUDICATED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "STATE IS RESPONSIBLE FOR SERVICES"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE CHARGES EXCEED THE CONTRACTED AMOUNT FOR THIS SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CHARGE EXCEEDS FEE SCHEDULE/MAXIMUM ALLOWABLE OR CONTRACTED/LEGISLATED FEE ARRANGEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM/SERVICE NOT COVERED BY THIS PAYER/CONTRACTOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "YOU MUST SEND THE CLAIM/SERVICE TO THE CORRECT PAYER/CONTRACTOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MISROUTED CLAIM. SEE THE PAYER'S CLAIM SUBMISSION INSTRUCTIONS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE SERVICE PERFORMED IS INCLUDED IN THE CASE RATE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CONSOLIDATED BILLING AND PAYMENT APPLIES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NETWORK BENEFITS HAVE BEEN APPLIED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE MEMBER IS ONLY RESPONSIBLE FOR THE COST SHARE (DEDUCTIBLE, COPAY AND COINSURANCE) AND ANY NON-COVERED AMOUNT AFTER THEY MEET THEIR BENEFIT LIMIT FOR A COVERED SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CO-PAYMENT AMOUNT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROC CODE/MOD PREVIOUSLY CONSIDERED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PREVIOUSLY PAID. PAYMENT FOR THIS CLAIM/SERVICE MAY HAVE BEEN PROVIDED IN A PREVIOUS PAYMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE SYSTEM IS UNABLE TO RESPOND AT THE MOMENT. PLEASE TRY REFRESHING THE PAGE (CLICK ON REFRESH AT THE TOP OF THE PAGE OR PRESS F5) OR TRY AGAIN AT A LATER TIME."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "YOUR SEARCH RETURNED NO RESULTS. PLEASE REVIEW YOUR SEARCH CRITERIA, INCLUDING THE PAYER NAME/PAYER ID, AND TRY AGAIN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS WAS DENIED BECAUSE THE CORRECTED CLAIM INFORMATION YOU SUPPLIED WILL BE APPLIED TO THE ORIGINAL CLAIM."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "FQHC PPS CLAIM WITH A LIDOS THAT MATCHES ANOTHER LIDOS ON A PREVIOUSLY SUBMITTED CLAIM AND ALL OF THE FOLLOWING MATCH: * BENEFICIARY HIC NUMBER * PROVIDER NUMBER * LINE ITEM DATE OF SERVICE IF APPROPRIATE, MAKE CORRECTIONS AND RESUBMIT A NEW CLAIM TO THE MAC."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "EXPENSES FOR EYEGLASSES OR CONTACT LENSES ARE NOT COVERED UNDER YOUR PLAN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "FINALIZED/DENIAL-THE CLAIM/LINE HAS BEEN DENIED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NO MATCHING PROCEDURE FOUND"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROCESSED IN ACCORDANCE WITH OUT OF NETWORK REIMBURSEMENT RULES."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROVIDER IS NOT ELIGIBLE FOR PROCEDURE ON DATE OF SERVICE,THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO,PROCEDURE NOT ALLOWED ON DATE OF SERVICE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PROVIDER IS NOT ELIGIBLE FOR PROCEDURE ON DATE OF SERVICE,THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO,PROCEDURE NOT ALLOWED ON DATE OF SERVICE,RECIPIENT ENROLLED IN MCO- CALL EVS FOR FURTHER INFORMATION."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "SPECIALTY MENTAL HEALTH AND/OR SUBSTANCE USE DISORDER CLAIM(S)MUST BE BILLED BY THE ASO.,THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO,RECIPIENT ENROLLED IN MCO- CALL EVS FOR FURTHER INFORMATION."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THE CALCULATED ALLOWED CHARGE AMOUNT EQUALS ZERO,RECIPIENT ENROLLED IN MCO- CALL EVS FOR FURTHER INFORMATION."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MISSING PROCEDURE CODE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "A SUBMITTED ELECTRONIC DATA INTERCHANGE (EDI) CLAIM HAS BEEN REJECTED AND IS NOT IN OUR CLAIM SYSTEM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM IS SAME AS PREVIOUS, SO IGNORING"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "PAYMENT FOR SERVICES IS DENIED. BENEFITS ARE ONLY AVAILABLE WHEN YOU RECEIVE A VALID REFERRAL FROM YOUR PRIMARY CARE PHYSICIAN (PCP) BEFORE RECEIVING THE SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "REFERRAL ABSENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NO BENEFIT IS DUE BECAUSE THIS CODE WAS BILLED FOR ZERO DOLLARS OR SHOULD HAVE BEEN BILLED FOR ZERO DOLLARS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS NON-PAYABLE CODE IS FOR REQUIRED REPORTING ONLY."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS CLAIM LINE IS BEING DISALLOWED BECAUSE THE SERVICES ARE NOT COVERED BY MEDICARE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "NON-COVERED CHARGE(S)."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS IS NOT A COVERED SERVICE/PROCEDURE/ EQUIPMENT/BED, HOWEVER PATIENT LIABILITY IS LIMITED TO AMOUNTS SHOWN IN THE ADJUSTMENTS UNDER GROUP 'PR'."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS SERVICE/EQUIPMENT/DRUG IS NOT COVERED UNDER THE PATIENT'S CURRENT BENEFIT PLAN."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "MISROUTED CLAIM. SEE THE PAYER'S CLAIM SUBMISSION INSTRUCTIONS."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CLAIM/SERVICE NOT COVERED BY THIS PAYER/CONTRACTOR. YOU MUST SEND THE CLAIM/SERVICE TO THE CORRECT PAYER/CONTRACTOR."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "COVERED UNDER PART D BENEFITS"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CONSULT PLAN BENEFIT DOCUMENTS/GUIDELINES FOR INFORMATION ABOUT RESTRICTIONS FOR THIS SERVICE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "CHARGES DO NOT MEET QUALIFICATIONS FOR EMERGENT/URGENT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Review, "THIS ITEM IS DENIED WHEN PROVIDED TO THIS PATIENT BY A NON-CONTRACT OR NON-DEMONSTRATION SUPPLIER."),
                

                //Secondary missing EOB
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.SecondaryMissingEob, "MEDICARE PAYMENT INFORMATION WAS NOT RECEIVED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.SecondaryMissingEob, "THE INFORMATION STILL NEEDED IS THE COPY OF THE EXPLANATION OF PART B MEDICARE BENEFITS (EOMB)"),

                //Timely Filing
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "THE TIME LIMIT FOR FILING HAS EXPIRED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "CLAIM/SERVICE NOT SUBMITTED WITHIN THE REQUIRED TIMEFRAME"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "TIMELY FILING"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "UNTIMELY FILED CLAIM"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "BENEFITS FOR THIS SERVICE ARE DENIED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "THE CLAIM WASN'T SUBMITTED ON TIME BASED ON THE PROVIDER'S CONTRACT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "THIS CLAIM MAY HAVE ALREADY BEEN REVIEWED AND PROCESSED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "FOR THE CLAIM TO BE RECONSIDERED, WE ASK THAT THE PROVIDER SEND US PROOF THAT THE CLAIM WAS SUBMITTED ON TIME."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "OPTIONS FOR THAT INCLUDE: AN ELECTRONIC DATA INTERCHANGE REPORT, SUBMISSION OR ACCEPTANCE REPORT, RECONSIDERATION FORM WITH AN EXPLANATION OR A BILLING SOFTWARE STATEMENT."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "THE PROVIDER MUST ALSO INDICATE IT IS A REPLACEMENT CLAIM OR CLEARLY MARK IT WITH THE WORD CORRECTED."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "CLAIM SUBMITTED AFTER FILING LIMIT"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.TimelyFiling, "THE TIME LIMIT FOR FILING HAS EXPIRED."),

                //Wrong Payer 
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "CLAIM NOT COVERED BY THIS PAYER/CONTRACTOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "SERVICE PAYABLE BY OTHER PRIMARY CARRIER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "OTHER CARRIER PAYMENT INFORMATION NEEDED BEFORE CLAIM CAN BE PROCESSED"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "CLAIM SUBMITTED TO INCORRECT PAYER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "YOU MUST SEND THE CLAIM TO THE CORRECT PAYER/CONTRACTOR"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "MISSING PLAN INFORMATION FOR OTHER INSURANCE"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "MEMBER IS ADDED TO WRONG PAYER"),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "MEMBER NOT FOUND, PLEASE CHECK THE DATA ENTERED OR TRY A DIFFERENT SEARCH TYPE."),
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.WrongPayer, "MEMBERNOTFOUND"),



                //Deductible
               // new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.Deductible, "CHARGE EXCEEDS FEE SCHEDULE/MAXIMUM ALLOWABLE OR CONTRACTED/LEGISLATED FEE ARRANGE- MENT.DEDUCTIBLE AMOUNT"),
               
                //Max Benefits
                new ClaimStatusExceptionReasonCategoryMap(ClaimStatusExceptionReasonCategoryEnum.MaxBenefits, "BENEFIT MAXIMUM FOR THIS TIME PERIOD OR OCCURRENCE HAS BEEN REACHED."),

                


            };

            await Task.Run(async () =>
            {
                foreach (var map in categoryMaps)
                {
                    if (!_dbContext.ClaimStatusExceptionReasonCategoryMaps.Any(cm => cm.ClaimStatusExceptionReasonText == map.ClaimStatusExceptionReasonText))
                    {
                        _dbContext.ClaimStatusExceptionReasonCategoryMaps.Add(map);
                    }
                }
            });
            await _dbContext.SaveChangesAsync();
            _logger.LogInformation("Seeded ClaimStatusExceptionReasonCategoryMaps");
        }
    }
}