// <auto-generated />
using System;
using MedHelpAuthorizations.Infrastructure.DataPipe.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedHelpAuthorizations.Infrastructure.DataPipe.Migrations
{
    [DbContext(typeof(DfStagingDbContext))]
    [Migration("20241218222439_AddedinsuranceFirstLastBilledOn")]
    partial class AddedinsuranceFirstLastBilledOn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblMapping", b =>
                {
                    b.Property<string>("Mapping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TableId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableSchema")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("tbl_Mappings", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblPatient", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("AddressStreetLine1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedOn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("HomePhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedOn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("PrimaryInsuranceId")
                        .HasColumnType("int");

                    b.Property<int?>("RenderingProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsiblePartyId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryInsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("SocialSecurityNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TertiaryInsuranceId")
                        .HasColumnType("int");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Patients", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblPatientInsuranceCard", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("ActiveDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<int?>("CardHolderId")
                        .HasColumnType("int");

                    b.Property<string>("CardHolderRelationship")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("CoInsurance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("CoPay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("EffectiveEndDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("EffectiveStartDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InactiveDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<int?>("InactivePosition")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceCardOrder")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("MemberNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlanType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_PatientInsuranceCards", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblPlaceOfService", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("FaxPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("Npi")
                        .HasColumnType("bigint")
                        .HasColumnName("NPI");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PlaceOfServiceCode")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceOfServiceId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_PlaceOfServices", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblProvider", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IsActive")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<string>("IsPhysiciansAssistant")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Npi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("SocialSecurityNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SpecialtyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Providers", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblProviderLocation", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderLocationId")
                        .HasColumnType("int");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_ProviderLocations", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblRemittance", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("CheckDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RemittanceFormType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RemittanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemittanceSource")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("UndistributedAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Remittances", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Entities.TblResponsibleParty", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("AddressStreetLine1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddressStreetLine2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ResponsiblePartiesId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_ResponsibleParties", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblAdjustmentCode", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("StgId");

                    b.ToTable("tbl_AdjustmentCodes", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblCardHolder", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CardHolderId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Employer")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_CardHolders", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblCharge", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("BilledToInsuranceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfServiceFrom")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("DateOfServiceTo")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcdCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcdCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcdCode3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcdCode4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceFirstBilledOn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("InsuranceLastBilledOn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifier1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifier2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifier3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modifier4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientFirstBillDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientInsuranceCard1Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientInsuranceCard2Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientInsuranceCard3Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastBillDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("PlaceOfServiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderingProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsiblePartyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Charges", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblClaimAdjustment", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("AdjustmentCodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ClaimAdjustmentsId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClaimNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("RemittenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_ClaimAdjustments", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblClaimPayment", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ClaimChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClaimNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimPaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedDate")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("RemittanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_ClaimPayments", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblInsurance", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("Active")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("AddressStreetLine1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddressStreetLine2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Insurances", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblLocation", b =>
                {
                    b.Property<int>("StgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StgId"));

                    b.Property<string>("AddressStreetLine1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressStreetLine2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("StgCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StgLastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StgLastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantClientString")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StgId");

                    b.ToTable("tbl_Locations", (string)null);
                });

            modelBuilder.Entity("MedHelpAuthorizations.Infrastructure.DataPipe.Models.TblLogDetail", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipeLineName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LogId")
                        .HasName("PK__tbl_LogD__5E5486485FE466E3");

                    b.ToTable("tbl_LogDetails", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
