using MedHelpAuthorizations.Application.Features.Reports.Queries.GetExpiringAuthorizations;
using MedHelpAuthorizations.Domain.Entities.Enums;
using System;

namespace MedHelpAuthorizations.Client.Infrastructure.Routes
{
    public static class ReportEndpoints
    {
        public static string ExportExpiringAuthorizations = "api/v1/tenant/Reports/exportexpiringauthorizations";

        public static string GetExpiringAuthorizations(GetPagedExpiringAuthorizationsQuery request)
        {
            return $"api/v1/tenant/Reports/expiringauthorizations?PageNumber={request.PageNumber}&PageSize={request.PageSize}";
        }

        public static string ExportClaimStatusDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportClaimStatusDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        }

        public static string ExportClaimStatusDenialDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom,
            DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId,
            string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), int? denialClaimStatusType = null, string dashboardType = null, bool hasGroupByKeySelector = false, bool hasProcedureDashboard = false,string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportClaimStatusDenialDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&denialClaimStatusType={denialClaimStatusType}&dashboardType={dashboardType}&hasGroupByKeySelector={hasGroupByKeySelector}&hasProcedureDashboard={hasProcedureDashboard}&fileName={fileName}";
        }

        public static string ExportClaimStatusInProcessDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? claimBilledFrom, DateTime? claimBilledTo,
            string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string procedureCodes = default(string), int? patientId = 0, string ClaimLineItemStatusId = null, string locationIds = default(string), string providerIds = default(string), DateTime? transactionDateFrom = null, DateTime? transactionDateTo = null, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportClaimStatusInProcessDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&claimBilledFrom={claimBilledFrom}" +
                   $"&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&procedureCodes={procedureCodes}&patientId={patientId}&claimLineItemStatusId={ClaimLineItemStatusId}&locationIds={locationIds}&providerIds={providerIds}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&fileName={fileName}";
        }
        public static string ExportInitialClaimStatusDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo,
            DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId,
            string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string dashboardType = default(string), string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportInitialClaimStatusDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&dashboardType={dashboardType}&fileName={fileName}";
        }

        public static string ExportInitialClaimStatusDenialDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo,
            DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string),
            string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string dashboardType = default(string), string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportInitialClaimStatusDenialDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&dashboardType={dashboardType}&fileName={fileName}";
        }

        public static string ExportInitialClaimStatusInProcessDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? claimBilledFrom, DateTime? claimBilledTo,
            string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string dashboardType = default(string), string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportInitialClaimStatusInProcessDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&dashboardType={dashboardType},&fileName={fileName}";
        }

        public static string ExportARAgingReportDetails = "api/v1/tenant/Reports/ExportARAgingReportDetails";
        public static string ExportARAgingReportSummary = "api/v1/tenant/Reports/ExportARAgingReportSummary";
        ///AA-157
        public static string GetAllReportsByCategory = "/api/v1/tenant/Reports/GetAllReportsByCategory";
        public static string GetReportByCategoryId = "/api/v1/tenant/Reports/GetReportByCategoryId";
        public static string GetReportDetailsById = "/api/v1/tenant/Reports/GetReportDetailsById";
        public static string SaveReport = "/api/v1/tenant/Reports/SaveReport";
        public static string GetFilteredReport = "/api/v1/tenant/Reports/GetFilteredReport";


        public static string ExportAvgDayToPayReportDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, bool hasAvgDayToPayByProvider = false, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportAvgDayToPayReportDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&hasAvgDayToPayByProvider={hasAvgDayToPayByProvider}&fileName={fileName}";
        }

        public static string FinicalSummaryExportDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null,string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/FinicalSummaryExportDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        }

        public static string ExportPaymentClaimStatusDetails(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportPaymentClaimStatusDetails?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        }

        //public static string ExportClaimStatusReport(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, string fileName = default(string))
        //{
        //    return $"api/v1/tenant/Reports/ClaimStatusReport?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        //} //EN-584

         public static string ExportClaimStatusReport(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ClaimStatusReport?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        } //EN-584

        public static string ExportClaimStatusDenialReport(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo, DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId, string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string providerIds = default(string), string commaDelimitedLineItemStatusIds = default(string), bool hasGroupByKeySelector = default(bool), ClaimStatusTypeEnum? claimStatusType = null, string claimStatusTypeValue = default(string), string dashboardType = null, string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ClaimStatusDenialReport?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&providerIds={providerIds}&commaDelimitedLineItemStatusIds={commaDelimitedLineItemStatusIds}&hasGroupByKeySelector={hasGroupByKeySelector}&claimStatusType={claimStatusType}&claimStatusTypeValue={claimStatusTypeValue}&dashboardType={dashboardType}&fileName={fileName}";
        } //EN-584

        public static string ExportInitialClaimStatusDenials(DateTime? createdOnFrom, DateTime? createdOnTo, DateTime? dateOfServiceFrom, DateTime? dateOfServiceTo, DateTime? transactionDateFrom, DateTime? transactionDateTo,
            DateTime? claimBilledFrom, DateTime? claimBilledTo, string clientInsuranceIds, string authTypeIds, int claimStatusBatchId,
            string exceptionReasonCategoryIds = default(string), string procedureCodes = default(string), int? patientId = 0, string locationIds = default(string), string dashboardType = default(string), string fileName = default(string))
        {
            return $"api/v1/tenant/Reports/ExportInitialClaimStatusDenials?createdOnFrom={createdOnFrom}&createdOnTo={createdOnTo}&dateOfServiceFrom={dateOfServiceFrom}&dateOfServiceTo={dateOfServiceTo}&transactionDateFrom={transactionDateFrom}&transactionDateTo={transactionDateTo}&claimBilledFrom={claimBilledFrom}&claimBilledTo={claimBilledTo}&clientInsuranceIds={clientInsuranceIds}&authTypeIds={authTypeIds}&claimStatusBatchId={claimStatusBatchId}&exceptionReasonCategoryIds={exceptionReasonCategoryIds}&procedureCodes={procedureCodes}&patientId={patientId}&locationIds={locationIds}&dashboardType={dashboardType}&fileName={fileName}";
        }//EN-584
    }
}
